### PR TITLE
[Bugfix] Avoid symbol conflicts in MakePackedAPI/MakeUnpackedAPI

### PR DESCRIPTION
**Pull request by Lunderberg**
PRs https://github.com/apache/tvm/pull/14913 and https://github.com/apache/tvm/pull/14914 made analogous changes to `MakePackedAPI` and `MakeUnpackedAPI` to handle subroutine calls. Both PRs introduced the same symbol, `tvm::tir::SubroutineCallRewriter`, a local utility to update internal calls to a modified function.  While each PR passed CI individually, and was therefore able to merge, having both changes caused a duplicate symbol.

This commit updates `MakePackedAPI` and `MakeUnpackedAPI` to place their local utilities into anonymous namespaces, avoiding the conflict.

### CODE REVIEW

**Review by csullivan — APPROVED** [review]

**Comment by tqchen** [comment]
does this hint perhaps we should have a common utility somehow as internal header

**Comment by csullivan** [comment]
Thanks @tqchen. Yeah, had the same thought when discussing offline with @Lunderberg but perhaps we can remove MakeUnpackedAPI altogether later.

In discussing with @Lunderberg it seems the special case handling MakeUnpackedAPI introduces for AOT should be able to be removed once annotations are used for whether a function requires packing or not. MakePackedAPI could then code generate the packed api when the functions are annotated and AOT functions would remain unpacked as they lack the annotation.

**Review by csullivan — APPROVED** [review]
