### ISSUE TITLE
[Bug] [Build Failure] build the tvm source code crash and threw "use of undeclared identifier 'f'"

### ISSUE THREAD

**Issue by jikechao** [apache/tvm#14878]
I update the TVM source code today (git_id: b4475b83) and rebuilt it.  The build crashed and threw a crash message:
![image](https://github.com/apache/tvm/assets/29506758/7bd79fd7-463c-4ca3-903f-96c789ad2611)

This crash was introduced after PR #14570 3 days before. 

### Environment

clang version 8.0.0-3~ubuntu16.04.1
TVM: git_id: b4475b83 (May 18, 2023)

### Steps to reproduce

git pull
make

cc @Lunderberg @kparzysz-quic @tqchen

**Comment by Lunderberg** [comment]
@jikechao Thank you for the bugix!  Since #14879, can we close this issue?
