### ISSUE TITLE
[Bug] Failed to import tvm.relax

### ISSUE THREAD

**Issue by zyhDuludulu** [apache/tvm#17553]
Hi, I encountered a problem when trying to import tvm.relax

```
$ python
$ import tvm.relax
```
### Expected behavior

import successfully

### Actual behavior
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/projects/tvm/python/tvm/relax/__init__.py", line 68, in <module>
    from .op.base import (
  File "/home/projects/tvm/python/tvm/relax/op/__init__.py", line 21, in <module>
    from . import _op_gradient, builtin, ccl, distributed, grad, image, memory, nn, op_attrs
  File "/home/projects/tvm/python/tvm/relax/op/_op_gradient.py", line 130, in <module>
    def add_grad(
  File "/home/projects/tvm/python/tvm/ir/op.py", line 241, in _register
    _ffi_api.RegisterOpAttr(op_name, attr_key, v, level)
AttributeError: module 'tvm.ir._ffi_api' has no attribute 'RegisterOpAttr'
```
### Environment

I'm working on Ubuntu 24.04, and the TVM version is 0.19.dev0

### Steps to reproduce

install TVM: https://tvm.apache.org/docs/install/from_source.html#install-from-source
I set the `USE_CUDA` option to ON by the way
then when I tried to import tvm.relax or tvm.relay, this error occurred.

I would be grateful if someone can hep me out!

**Comment by Comet-hash** [comment]
I encountered the same issue, and it was resolved by switching the installed LLVM version to 15 and rebuilding.

**Comment by tqchen** [comment]
this is likely due to the fact that the libtvm is not the most up to date version, make sure you build completes and points to the right version

**Comment by zyhDuludulu** [comment]
Thanks! the problem solved
I found I did not build the lib correctly and the error reported is 'cannot find lib -lxml2'

Use terminal outside instead of the terminal in VScode solved this problem, may be my env activated in python extension mislead cmake

Hope this can help those who encountered the same situation

**Comment by sidsingla** [comment]
In the terminal outside VSCode also, I am facing the issue. Any fix or solution to this problem?
