### ISSUE TITLE
[CI Problem] Windows build fails when compiling RPC server

### ISSUE THREAD

**Issue by Mousius** [apache/tvm#11220]
```
C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\src\runtime\rpc\rpc_channel_logger.h(99,11): error C3646: 'PosixWrite': unknown override specifier (compiling source file C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\src\runtime\rpc\rpc_endpoint.cc) [C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\build\tvm_runtime_objs.vcxproj]
C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\src\runtime\rpc\rpc_channel_logger.h(99,21): error C2059: syntax error: '(' (compiling source file C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\src\runtime\rpc\rpc_endpoint.cc) [C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\build\tvm_runtime_objs.vcxproj]
C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\src\runtime\rpc\rpc_channel_logger.h(99,65): error C2334: unexpected token(s) preceding '{'; skipping apparent function body (compiling source file C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\src\runtime\rpc\rpc_endpoint.cc) [C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\build\tvm_runtime_objs.vcxproj]
C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\src\runtime\rpc\rpc_channel_logger.h(103,11): error C3646: 'PosixRead': unknown override specifier (compiling source file C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\src\runtime\rpc\rpc_endpoint.cc) [C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\build\tvm_runtime_objs.vcxproj]
C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\src\runtime\rpc\rpc_channel_logger.h(103,20): error C2059: syntax error: '(' (compiling source file C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\src\runtime\rpc\rpc_endpoint.cc) [C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\build\tvm_runtime_objs.vcxproj]
C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\src\runtime\rpc\rpc_channel_logger.h(103,58): error C2334: unexpected token(s) preceding '{'; skipping apparent function body (compiling source file C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\src\runtime\rpc\rpc_endpoint.cc) [C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\build\tvm_runtime_objs.vcxproj]
C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\src\runtime\rpc\rpc_channel_logger.h(99,11): error C3646: 'PosixWrite': unknown override specifier (compiling source file C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\src\runtime\rpc\rpc_event_impl.cc) [C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\build\tvm_runtime_objs.vcxproj]
C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\src\runtime\rpc\rpc_channel_logger.h(99,21): error C2059: syntax error: '(' (compiling source file C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\src\runtime\rpc\rpc_event_impl.cc) [C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\build\tvm_runtime_objs.vcxproj]
C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\src\runtime\rpc\rpc_channel_logger.h(99,65): error C2334: unexpected token(s) preceding '{'; skipping apparent function body (compiling source file C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\src\runtime\rpc\rpc_event_impl.cc) [C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\build\tvm_runtime_objs.vcxproj]
C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\src\runtime\rpc\rpc_channel_logger.h(103,11): error C3646: 'PosixRead': unknown override specifier (compiling source file C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\src\runtime\rpc\rpc_event_impl.cc) [C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\build\tvm_runtime_objs.vcxproj]
C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\src\runtime\rpc\rpc_channel_logger.h(103,20): error C2059: syntax error: '(' (compiling source file C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\src\runtime\rpc\rpc_event_impl.cc) [C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\build\tvm_runtime_objs.vcxproj]
C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\src\runtime\rpc\rpc_channel_logger.h(103,58): error C2334: unexpected token(s) preceding '{'; skipping apparent function body (compiling source file C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\src\runtime\rpc\rpc_event_impl.cc) [C:\Miniconda\envs\tvm-build\conda-bld\tvm-package_1651695603375\work\build\tvm_runtime_objs.vcxproj]
```

### Branch/PR Failing

I think this was Introduced in #10967 which failed to build yet was still merged, unsure how that happened 🙀 

### Jenkins Link

[Provide a link to the specific run that has failed.
](https://github.com/apache/tvm/runs/6296517893?check_suite_focus=true#step:4:1043)

cc @mehrdadh @areusch @kparzysz-quic

**Comment by mehrdadh** [comment]
@Mousius thanks for reporting this! Will investigate today

**Comment by areusch** [comment]
sorry for this break! can we close now that the revert is merged?
