### PR TITLE
[Runtime] CutensorMap support

### PR DESCRIPTION
**Pull request by spectrometerHBH**
This pull request enables support for CutensorMap in both the IR and runtime layers.

### CODE REVIEW

**Comment by tqchen** [comment]
cc @Hzfengsy

File: src/runtime/cuda/cuda_device_api.cc [hunk 1]
```diff
@@ -357,5 +357,188 @@ TVM_DLL int GetCudaDeviceCount() {
 
 TVM_FFI_REGISTER_GLOBAL("runtime.GetCudaDeviceCount").set_body_typed(GetCudaDeviceCount);
 
+TVM_FFI_REGISTER_GLOBAL("runtime.cuTensorMapEncodeTiled")
```
Comment (tqchen) [inline src/runtime/cuda/cuda_device_api.cc:383]: add comments about the calling convention

File: include/tvm/ir/type.h [hunk 2]
```diff
@@ -312,5 +312,26 @@ class FuncType : public Type {
   TVM_DEFINE_OBJECT_REF_METHODS(FuncType, Type, FuncTypeNode);
 };
 
+class TensorMapTypeNode : public TypeNode {
+ public:
+  void VisitAttrs(AttrVisitor* v) { v->Visit("span", &span); }
```
Comment (tqchen) [inline include/tvm/ir/type.h:321]: does not have to be now, see https://github.com/apache/tvm/pull/18098 to transition to new reflection, i can do that after erge as well

File: include/tvm/ir/type.h [hunk 3]
```diff
@@ -312,5 +312,26 @@ class FuncType : public Type {
   TVM_DEFINE_OBJECT_REF_METHODS(FuncType, Type, FuncTypeNode);
 };
 
+class TensorMapTypeNode : public TypeNode {
```
Comment (tqchen) [inline include/tvm/ir/type.h:319]: add docstring about this type

**Review by tqchen — COMMENTED** [review]
overall looks good, please fix lint

**Comment by Hzfengsy** [comment]
cc @LeiWang1999

**Review by tqchen — APPROVED** [review]

File: src/runtime/meta_data.h [hunk 4]
```diff
@@ -58,6 +58,7 @@ struct FunctionInfo {
   std::string name;
   std::vector<DLDataType> arg_types;
   std::vector<std::string> launch_param_tags;
+  std::vector<int> arg_is_tensormap;
```
Comment (tqchen) [inline src/runtime/meta_data.h]: update this to arg_extra_tags;

Make 
```c++
enum class ArgExtraTags : int {
   kNone = 0,
   kTensorMap = 1
}
```

**Review by tqchen — CHANGES_REQUESTED** [review]

**Review by tqchen — APPROVED** [review]

**Comment by w1049** [comment]
Should we add a version check? `CUtensorMap` causes compilation failures on CUDA versions below 12.

**Comment by tqchen** [comment]
@w1049 can you elaborate on the failure cases?

**Comment by w1049** [comment]
> @w1049 can you elaborate on the failure cases?

The `CUtensorMap` feature was introduced in CUDA 12. When attempting to compile with CUDA 11.8, the build fails because `CUtensorMap` is not available in `cuda.h`. The error message appears as:
```
tvm/src/runtime/cuda/cuda_device_api.cc:525: undefined reference to `cuTensorMapEncodeTiled'
```
Similar issue: https://github.com/llvm/llvm-project/issues/64529

**Comment by tqchen** [comment]
i see, seems we should guard the registration of `runtime.cuTensorMapEncodeTiled` with `#if (CUDA_VERSION >= 12000)` macro.

**Comment by tqchen** [comment]
fixed by https://github.com/apache/tvm/pull/18107 thanks @w1049
