### PR TITLE
[Fix][Relax][ONNX] Relax op normalization for onnx subgraphs

### PR DESCRIPTION
**Pull request by cbalint13**
### Summary
Onnx subgraph imports should also normalize and generate ty_info for its ops, this is broken since #19853 refactor.

### Issue

```
tests/python/relax/test_frontend_onnx.py:11581: in test_if_subgraph
    tvm_model = from_onnx(model, keep_params_in_input=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/usr/lib/python3.15/site-packages/tvm/relax/frontend/onnx/onnx_frontend.py:6283: in from_onnx
    return g.from_onnx(graph, opset)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
/usr/lib/python3.15/site-packages/tvm/relax/frontend/onnx/onnx_frontend.py:5823: in from_onnx
    self._construct_nodes(graph)
/usr/lib/python3.15/site-packages/tvm/relax/frontend/onnx/onnx_frontend.py:5969: in _construct_nodes
    then_expr = self._convert_subgraph(self.bb, attr["then_branch"])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/usr/lib/python3.15/site-packages/tvm/relax/frontend/onnx/onnx_frontend.py:6166: in _convert_subgraph
    op = self._convert_operator(op_name, inputs, attr, self.opset)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/usr/lib/python3.15/site-packages/tvm/relax/frontend/onnx/onnx_frontend.py:6117: in _convert_operator
    sym = op_function(self.bb, inputs, attrs, [self._nodes, self._params])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/usr/lib/python3.15/site-packages/tvm/relax/frontend/onnx/onnx_frontend.py:1882: in _impl_v11
    ndim = len(inputs[0].ty.shape)
               ^^^^^^^^^^^^^^^^^^
E   AttributeError: 'Type' object has no attribute 'shape'
```

### Fix

Add conversion check, normalize and populate the final relax op with ty_info regardless of the graph context.

### CODE REVIEW

**Comment by cbalint13** [comment]
cc @tlopex, @guan404ming

**Review by tlopex — APPROVED** [review]
LGTM
