### PR TITLE
Cut pytest-lazy-fixture

### PR DESCRIPTION
**Pull request by Liam-Sturge**
Pytest-lazy-fixture doesn't work with `pytest==8.0.0`

The following error occurs when pytest-lazy-fixture is called:

    `AttributeError: 'CallSpec2' object has no attribute 'funcargs'`

This has been raised as an issue on the pytest-lazy-fixture project, but the repository is not in active development. See https://github.com/TvoroG/pytest-lazy-fixture/issues/65 for details.

TVM project code-base makes very little reference to pytest-lazy-fixture, so this patch removes the library from the project altogether, in order to resolve the problem.

CC @neildhickey @lhutton1 @tqchen

### CODE REVIEW

**Review by neildhickey — APPROVED** [review]
@Liam-Sturge thanks for this contribution.

We'll have to regenerate the correct docker images and update once this change has gone in.

Perhaps we can put up a draft review pointing to the new docker images once they are built? Just to be doubly sure CI works still

**Review by lhutton1 — APPROVED** [review]
LGTM! The checks on the docker image have passed: https://github.com/apache/tvm/pull/16522

**Comment by lhutton1** [comment]
Thanks @Liam-Sturge @neildhickey!
