### PR TITLE
[Arith] MLIR PresburgerSet compile fix mlir >= 160

### PR DESCRIPTION
**Pull request by cbalint13**
Hi folks,

Some fixes for MLIR based analyzer module introduced by #14690 .

---

* Make CMake at par with LLVM info:
```
{...}
-- Use llvm-config=llvm-config-64
-- LLVM libdir: /usr/lib64
-- Found MLIR
-- Build with MLIR
-- Set TVM_MLIR_VERSION=160
-- Found LLVM_INCLUDE_DIRS=/usr/include
{...}
--    USE_MKL                            : OFF
--    USE_MLIR                           : ON
--    USE_MSVC_MT                        : OFF
{...}
```

* Fix several compilation errors:
```
error: cannot convert 'llvm::SmallVector<long int>' to 'llvm::ArrayRef<mlir::presburger::MPInt>'
error: no matching function for call to 'tvm::IntImm::IntImm(tvm::runtime::DataType, mlir::presburger::MPInt&)'
note:   no known conversion for argument 2 from 'mlir::presburger::MPInt' to 'int64_t' {aka 'long int'}
```

Tested using: ```llvm/mlir 16.0.6```, ```llvm/mlir 15.0.7```,  ```llvm/mlir 17.0.0rc3```

Thanks,
~Cristian.

Cc @multiverstack-intellif , @wrongtest-intellif , @vinx13, @Hzfengsy , @junrushao , @tqchen

### CODE REVIEW

**Review by junrushao — APPROVED** [review]
Thanks for the bugfixes! Definitely not an expert here, and do you think we need to add a test for changes introduced in presurger_set.cc?

**Comment by cbalint13** [comment]
> Thanks for the bugfixes! Definitely not an expert here, and do you think we need to add a test for changes introduced in presurger_set.cc?

@junrushao ,

Me either, not expert on this topic, unsure how #14690 passed it's own test (can't see related CI logs).
Since here we have compilation fixes (no changes), the  #14690 test case included should be sufficient.

---

Let's wait the tests to pass in green, reported issue here might be related to:
 **(a)** a different ```mlir = 16``` version on my side
 **(b)** a newer ```gcc 13``` not willing to infer casts  (unplausible)

If **(a)**  will adjust this PR with some little ```#if version``` checks (LLVM/MLIR  comes with frequent API changes).

Let's also ask authors: @multiverstack-intellif , @wrongtest-intellif

**Comment by cbalint13** [comment]
> If **(a)** will adjust this PR with some little `#if version` to keep pace with MLIR API changes (mlir >= 15, as expected).
> Let's also ask authors: @multiverstack-intellif , @wrongtest-intellif

I've updated the PR to be consistent with all ```mlir >= 15```  releases.
Elaborated for: ```llvm/mlir 15.0.7```, ```llvm/mlir 16.0.6```, ```llvm/mlir 17.0.0rc3```.

**Comment by multiverstack-intellif** [comment]
> > Thanks for the bugfixes! Definitely not an expert here, and do you think we need to add a test for changes introduced in presurger_set.cc?
> 
> @junrushao ,
> 
> Me either, not expert on this topic, unsure how #14690 passed it's own test (can't see related CI logs). Since here we have compilation fixes (no changes), the #14690 test case included should be sufficient.
> 
> Let's wait the tests to pass in green, reported issue here might be related to: **(a)** a different `mlir = 16` version on my side **(b)** a newer `gcc 13` not willing to infer casts (unplausible)
> 
> If **(a)** will adjust this PR with some little `#if version` to keep pace with MLIR API changes (mlir >= 15, as expected).
> 
> Let's also ask authors: @multiverstack-intellif , @wrongtest-intellif

I believe it's because of a), USE_MLIR is not turned ON in CI test, AFAIK, and only LLVM 14 & 15 is tested locally when  #14690 is submitted.

**Comment by junrushao** [comment]
Sounds great, and it seems that we all agree with the changes being made! Will merge it in as soon as the CI is green.

**Comment by cbalint13** [comment]
> 

@multiverstack-intellif , @junrushao 

Trying to tackle similar issue as described at [interblock analisys](https://github.com/multiverstack-intellif/tvm-rfcs/blob/improve_intset/rfcs/0099-introduce-PresburgerSet.md#interblock-analysis) I noticed it can't compile on newer mlir.
I think just like LLVM, MLIR will have frequent api changes across releases, so maintenance like this PR will be needed.

---

To refresh, this PR now covers (tested on ) llvm/mlir: ```15.0.7```, ```16.0.6``` and ```17.0.0rc3```.

**Comment by junrushao** [comment]
Thanks @cbalint13! This is merged!
