### ISSUE TITLE
[Bug] `concat([x], axis=1)` return random results

### ISSUE THREAD

**Issue by ganler** [apache/tvm#11895]
```python
import tvm
from tvm import relay
import numpy as np

x1_shape = (2, 1)

x1 = relay.var("x1", shape=x1_shape, dtype='int64')
concatenate = relay.op.concatenate([x1], axis=1)

f = relay.Function([x1], concatenate)

x1_val = np.array([[6], [5]], dtype='int64')

op_res = relay.create_executor('graph', device=tvm.cpu(), target='llvm').evaluate(f)(x1_val)
print(op_res)
print(f'should be equal to {x1_val}')
```

### Expected behavior

`op_res` should be same as `[[6], [5]]`.

### Actual behavior

1st try:

![image](https://user-images.githubusercontent.com/38074777/175721475-be886e37-476e-4785-a37f-bf4472e7420f.png)

2nd try:

![image](https://user-images.githubusercontent.com/38074777/175721486-d86daa24-2ddc-459c-add6-4f0384f564f8.png)

3rd try:

![image](https://user-images.githubusercontent.com/38074777/175721504-546fe35b-f747-4cef-ad2e-3a4c8e70d50c.png)

### Environment

ed638ef6db007772cbf84b13c26836a8a53706b3 on Ubuntu 20.04.

cc: @masahi

**Comment by lileidev** [comment]
I tried the sample code to reproduce, but get bellow error:
Traceback (most recent call last):
  File "5.py", line 1, in <module>
    import tvm
  File "/home/larry/.wine/drive_d/tvm/python/tvm/__init__.py", line 42, in <module>
    from .ir import IRModule
  File "/home/larry/.wine/drive_d/tvm/python/tvm/ir/__init__.py", line 33, in <module>
    from .memory_pools import (
  File "/home/larry/.wine/drive_d/tvm/python/tvm/ir/memory_pools.py", line 38, in <module>
    class PoolInfoProperties(Object):
  File "/home/larry/.wine/drive_d/tvm/python/tvm/_ffi/registry.py", line 69, in register
    check_call(_LIB.TVMObjectTypeKey2Index(c_str(object_name), ctypes.byref(tidx)))
  File "/home/larry/.wine/drive_d/tvm/python/tvm/_ffi/base.py", line 348, in check_call
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  81: 0xffffffffffffffff
  80: _start
  79: __libc_start_main
        at ../csu/libc-start.c:308
  78: Py_BytesMain
  77: Py_RunMain
  76: PyRun_SimpleFileExFlags
  75: 0x000000000067e470
  74: 0x000000000067e3ce
  73: 0x000000000067e350
  72: PyEval_EvalCode
  71: _PyEval_EvalCodeWithName
  70: _PyEval_EvalFrameDefault
  69: PyImport_ImportModuleLevelObject
  68: _PyObject_CallMethodIdObjArgs
  67: 0x00000000005f4400
  66: _PyFunction_Vectorcall
  65: _PyEval_EvalFrameDefault
  64: _PyFunction_Vectorcall
  63: _PyEval_EvalFrameDefault
  62: _PyFunction_Vectorcall
  61: _PyEval_EvalFrameDefault
  60: _PyFunction_Vectorcall
  59: _PyEval_EvalFrameDefault
  58: _PyFunction_Vectorcall
  57: _PyEval_EvalCodeWithName
  56: _PyEval_EvalFrameDefault
  55: PyVectorcall_Call
  54: 0x00000000005c4a3f
  53: 0x00000000006003a3
  52: PyEval_EvalCode
  51: _PyEval_EvalCodeWithName
  50: _PyEval_EvalFrameDefault
  49: PyImport_ImportModuleLevelObject
  48: _PyObject_CallMethodIdObjArgs
  47: 0x00000000005f4400
  46: _PyFunction_Vectorcall
  45: _PyEval_EvalFrameDefault
  44: _PyFunction_Vectorcall
  43: _PyEval_EvalFrameDefault
  42: _PyFunction_Vectorcall
  41: _PyEval_EvalFrameDefault
  40: _PyFunction_Vectorcall
  39: _PyEval_EvalFrameDefault
  38: _PyFunction_Vectorcall
  37: _PyEval_EvalCodeWithName
  36: _PyEval_EvalFrameDefault
  35: PyVectorcall_Call
  34: 0x00000000005c4a3f
  33: 0x00000000006003a3
  32: PyEval_EvalCode
  31: _PyEval_EvalCodeWithName
  30: _PyEval_EvalFrameDefault
  29: PyImport_ImportModuleLevelObject
  28: _PyObject_CallMethodIdObjArgs
  27: 0x00000000005f4400
  26: _PyFunction_Vectorcall
  25: _PyEval_EvalFrameDefault
  24: _PyFunction_Vectorcall
  23: _PyEval_EvalFrameDefault
  22: _PyFunction_Vectorcall
  21: _PyEval_EvalFrameDefault
  20: _PyFunction_Vectorcall
  19: _PyEval_EvalFrameDefault
  18: _PyFunction_Vectorcall
  17: _PyEval_EvalCodeWithName
  16: _PyEval_EvalFrameDefault
  15: PyVectorcall_Call
  14: 0x00000000005c4a3f
  13: 0x00000000006003a3
  12: PyEval_EvalCode
  11: _PyEval_EvalCodeWithName
  10: _PyEval_EvalFrameDefault
  9: _PyFunction_Vectorcall
  8: _PyEval_EvalCodeWithName
  7: _PyEval_EvalFrameDefault
  6: _PyObject_MakeTpCall
  5: 0x00007fb5add2a9db
  4: _ctypes_callproc
  3: 0x00007fb5aeaba409
  2: 0x00007fb5aeabaff4
  1: TVMObjectTypeKey2Index
  0: tvm::runtime::Object::TypeKey2Index(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
  File "/home/larry/.wine/drive_d/tvm/src/runtime/object.cc", line 165
TVMError: 
---------------------------------------------------------------
An error occurred during the execution of TVM.
For more information, please see: https://tvm.apache.org/docs/errors.html
---------------------------------------------------------------
  Check failed: (it != type_key2index_.end()) is false: Cannot find type ir.PoolInfoProperties. Did you forget to register the node by TVM_REGISTER_NODE_TYPE ?

**Comment by ganler** [comment]
I doubled checked that but I can still reproduce it (in the commit version I attached which is very recent). I think the operators used here are very common that it is not likely to be not registering them.

**Comment by masahi** [comment]
what happens if you revert the commits https://github.com/apache/tvm/pull/11341 and https://github.com/apache/tvm/pull/11800?

**Comment by ganler** [comment]
Just tried the commit right before https://github.com/apache/tvm/pull/11800, this issue is still there. am trying https://github.com/apache/tvm/pull/11341 ~1 now.

![image](https://user-images.githubusercontent.com/38074777/175756184-89283ae6-47f5-450d-9b9c-1ccda6374979.png)

**Comment by ganler** [comment]
@masahi So a1d95ec1ea30ac70e544a3cf10c839e228d407bf (https://github.com/apache/tvm/pull/11341 ~1) is correct as follows:

![image](https://user-images.githubusercontent.com/38074777/175756318-cb0d94ac-7bee-4f11-a7dd-24c043751a6b.png)

I also directly tried https://github.com/apache/tvm/pull/11341 it fails:

![image](https://user-images.githubusercontent.com/38074777/175756384-78d124df-0a27-4228-bb92-c20d41bdd823.png)

Therefore, it is highly likely that this bug is introduced by https://github.com/apache/tvm/pull/11341.

**Comment by masahi** [comment]
@shtinsa Can you take a look?

**Comment by shtinsa** [comment]
Hello, fix is here: https://github.com/apache/tvm/pull/11907
