### PR TITLE
[TARGET] Specify correct `mcpu` for Metal target tags

### PR DESCRIPTION
**Pull request by mshr-h**
As per title.

### CODE REVIEW

**Comment by mshr-h** [comment]
Fixes errors below.
```
/workspace/src/target/llvm/llvm_instance.cc:227: Error: Using LLVM 15.0.7 with `-mcpu=apple-m4` is not valid in `-mtriple=arm64-apple-macos`, using default `-mcpu=generic`
```

link to recent ci log: https://ci.tlcpack.ai/blue/organizations/jenkins/tvm-gpu/detail/PR-18818/3/pipeline/100/

**Comment by tqchen** [comment]
@mshr-h do u mind look at ci issue

**Comment by mshr-h** [comment]
windows and macos failures should be solved with #18818

**Review by tqchen — APPROVED** [review]
